"""Authentication: login/logout, one-time admin setup, self-registration."""
import re

from flask import (
    Blueprint, abort, current_app, flash, redirect, render_template, request, session, url_for,
)
from pathlib import Path

from .geo import geo_thread_lookup
from .models import LoginEvent, Setting, User, db, utcnow
from .security import audit, check_csrf, client_ip, csrf_token

bp = Blueprint("auth", __name__)

USERNAME_RE = re.compile(r"^[a-zA-Z0-9._@-]{3,64}$")
COMMON_PASSWORDS = {"password", "password1", "12345678", "qwertyuiop", "letmein123", "admin12345"}


def current_user():
    if not session.get("uid"):
        return None
    return db.session.get(User, session["uid"])


def _setup_key_path():
    return Path(current_app.root_path).parent / "instance" / "SETUP_KEY"


def setup_key_required():
    """The one-time setup key generated by the installer (root-only file)."""
    p = _setup_key_path()
    if not p.exists():
        return None
    return p.read_text().strip()


def admin_exists():
    return db.session.query(User.id).filter(User.role == "admin").first() is not None


def _validate_password(pw):
    if len(pw) < 10:
        return "Password must be at least 10 characters."
    if pw.lower() in COMMON_PASSWORDS:
        return "That password is too common."
    if pw.lower() in ("", None):
        return "Password required."
    return None


def _record_login_event(user, success):
    ev = LoginEvent(
        user_id=user.id if user else None,
        username=(user.username if user else request.form.get("username", ""))[:64],
        success=success, ip=client_ip(),
        user_agent=request.headers.get("User-Agent", "")[:250],
    )
    db.session.add(ev)
    return ev


@bp.route("/setup", methods=["GET", "POST"])
def setup():
    """ONE-TIME admin registration. Requires the installer-generated setup key.
    After the first admin is created this endpoint is permanently disabled."""
    if admin_exists():
        abort(404)
    key = setup_key_required()
    if key is None:
        return render_template("auth/setup.html", locked=True, key_ok=False), 403
    error = None
    if request.method == "POST":
        if not check_csrf():
            abort(400, "Invalid CSRF token")
        supplied = (request.form.get("setup_key") or "").strip()
        if supplied != key:
            error = "Invalid setup key. Check the value generated by the installer (/opt/netai/instance/SETUP_KEY)."
        else:
            username = (request.form.get("username") or "").strip()
            pw, pw2 = request.form.get("password") or "", request.form.get("password2") or ""
            if not USERNAME_RE.match(username):
                error = "Username must be 3-64 chars: letters, digits, dot, dash, underscore or @."
            else:
                err = _validate_password(pw)
                if err:
                    error = err
                elif pw != pw2:
                    error = "Passwords do not match."
                else:
                    u = User(username=username, role="admin")
                    u.set_password(pw)
                    db.session.add(u)
                    Setting.put("admin_setup_complete", "1")
                    Setting.put("allow_signup", "1" if current_app.config["ALLOW_SIGNUP_DEFAULT"] else "0")
                    db.session.commit()
                    try:
                        _setup_key_path().unlink()   # burn the one-time key
                    except OSError:
                        pass
                    audit("admin.setup", f"one-time admin registration: {username}")
                    flash("Administrator account created. This setup page is now permanently disabled.", "success")
                    return redirect(url_for("auth.login"))
    return render_template("auth/setup.html", error=error, key_ok=True,
                           username=request.form.get("username", "")), (200 if not error else 400)


@bp.route("/login", methods=["GET", "POST"])
def login():
    if not admin_exists():
        return redirect(url_for("auth.setup"))
    nxt = request.args.get("next") or request.form.get("next") or url_for("main.index")
    if not nxt.startswith("/"):        # prevent open redirect
        nxt = url_for("main.index")
    if request.method == "POST":
        if not check_csrf():
            abort(400, "Invalid CSRF token")
        username = (request.form.get("username") or "").strip()
        pw = request.form.get("password") or ""
        u = db.session.query(User).filter(User.username == username).first()
        fail_msg = "Invalid credentials."
        if u is not None and u.is_locked:
            _record_login_event(u, False)
            db.session.commit()
            return render_template("auth/login.html", next=nxt, username=username,
                                   error="Account temporarily locked after repeated failures. Try again later."), 423
        if u is None or not u.check_password(pw):
            if u is not None:
                u.failed_attempts = (u.failed_attempts or 0) + 1
                if u.failed_attempts >= current_app.config["LOGIN_MAX_ATTEMPTS"]:
                    import datetime as _dt

                    u.locked_until = utcnow() + _dt.timedelta(seconds=current_app.config["LOGIN_LOCKOUT_SECONDS"])
                    audit("auth.lockout", f"account {username} locked after repeated failures")
                    fail_msg = f"Too many failed attempts. Account locked for {current_app.config['LOGIN_LOCKOUT_SECONDS'] // 60} minutes."
            ev = _record_login_event(u, False)
            db.session.commit()
            flash(fail_msg, "danger")
            return render_template("auth/login.html", next=nxt, username=username), 401
        if u.is_locked:
            _record_login_event(u, False)
            db.session.commit()
            return render_template("auth/login.html", next=nxt, username=username,
                                   error=f"Account temporarily locked. Try again later."), 423
        if not u.is_active:
            _record_login_event(u, False)
            db.session.commit()
            flash("This account has been disabled by an administrator.", "danger")
            return render_template("auth/login.html", next=nxt, username=username), 403
        # success: reset counters, fixate fresh session
        session.clear()
        u.failed_attempts = 0
        u.locked_until = None
        u.last_login_at = utcnow()
        u.last_ip = client_ip()
        ev = _record_login_event(u, True)
        db.session.commit()
        geo_thread_lookup(client_ip())      # resolve location in background
        session["uid"] = u.id
        session["role"] = u.role
        session["username"] = u.username
        session.permanent = True
        return redirect(nxt)
    return render_template("auth/login.html", next=nxt, username="")


@bp.route("/logout", methods=["POST"])
def logout():
    if not check_csrf():
        abort(400, "Invalid CSRF token")
    audit("auth.logout", session.get("username", ""))
    session.clear()
    flash("Signed out.", "success")
    return redirect(url_for("auth.login"))


@bp.route("/register", methods=["GET", "POST"])
def register():
    if Setting.get("allow_signup", "1" if current_app.config["ALLOW_SIGNUP_DEFAULT"] else "0") != "1":
        flash("Self-registration is disabled. Ask an administrator for an account.", "warn")
        return redirect(url_for("auth.login"))
    error = None
    if request.method == "POST":
        if not check_csrf():
            abort(400, "Invalid CSRF token")
        username = (request.form.get("username") or "").strip()
        pw, pw2 = request.form.get("password") or "", request.form.get("password2") or ""
        if not USERNAME_RE.match(username):
            error = "Username must be 3-64 chars: letters, digits, dot, dash, underscore or @."
        elif _validate_password(pw):
            error = _validate_password(pw)
        elif pw != pw2:
            error = "Passwords do not match."
        elif db.session.query(User.id).filter(User.username == username).first():
            error = "Username already taken."
        else:
            u = User(username=username, role="user")
            u.set_password(pw)
            db.session.add(u)
            db.session.commit()
            audit("user.register", username)
            flash("Account created - you can sign in now.", "success")
            return redirect(url_for("auth.login"))
    return render_template("auth/register.html", error=error, username=request.form.get("username", ""))


@bp.route("/account", methods=["GET", "POST"])
def account():
    u = current_user()
    if u is None:
        return redirect(url_for("auth.login"))
    error = None
    if request.method == "POST":
        if not check_csrf():
            abort(400, "Invalid CSRF token")
        cur = request.form.get("current") or ""
        new, new2 = request.form.get("password") or "", request.form.get("password2") or ""
        if not u.check_password(cur):
            error = "Current password is incorrect."
        elif _validate_password(new):
            error = _validate_password(new)
        elif new != new2:
            error = "New passwords do not match."
        else:
            u.set_password(new)
            u.must_reset = False
            db.session.commit()
            audit("user.password_change", u.username)
            flash("Password updated.", "success")
            return redirect(url_for("main.index"))
    if u.must_reset:
        flash("An administrator issued you a temporary password. Please set a new one.", "warn")
    return render_template("auth/account.html", user=u, error=error)


@bp.app_context_processor
def inject_globals():
    from flask import session as s

    return dict(csrf_token=csrf_token, current_username=s.get("username", ""),
                current_role=s.get("role", ""), site_name=current_app.config["SITE_NAME"],
                site_version=current_app.config.get("SITE_VERSION", ""))
